#!/bin/bash

# PR4-PR6 Test Artifact Generation Script
# Generates all required evidence for validation

echo "🧪 Generating PR4-PR6 Test Artifacts..."

# Create artifacts directory
mkdir -p artifacts/coverage artifacts/performance artifacts/screenshots artifacts/audit

echo "📊 Step 1: Running Vitest with coverage..."
npm run test -- --coverage --reporter=json --reporter=html --outputFile=artifacts/coverage/vitest-results.json 2>&1 | tee artifacts/vitest-output.log

echo "🎭 Step 2: Running Playwright E2E tests..."
npx playwright test --reporter=json --reporter=html 2>&1 | tee artifacts/playwright-output.log

echo "⚡ Step 3: Running k6 load tests..."
k6 run tests/loadtest.k6.js --out json=artifacts/performance/k6-results.json 2>&1 | tee artifacts/k6-output.log || echo "k6 not installed or failed"

echo "🔍 Step 4: Running Lighthouse performance audit..."
npx lighthouse https://arabisch-online-leren.vercel.app --output=html --output=json --output-path=artifacts/performance/lighthouse 2>&1 | tee artifacts/lighthouse-output.log || echo "Lighthouse failed or not accessible"

echo "♿ Step 5: Running axe accessibility tests..."
npx @axe-core/cli https://arabisch-online-leren.vercel.app --save artifacts/performance/axe-results.json 2>&1 | tee artifacts/axe-output.log || echo "axe-core not installed"

echo "📸 Step 6: Screenshots already generated by Playwright"

echo "✅ Artifact generation complete!"
echo "📁 Artifacts saved to: ./artifacts/"
echo ""
echo "📋 Generated files:"
ls -lh artifacts/
ls -lh artifacts/coverage/ 2>/dev/null || echo "No coverage artifacts"
ls -lh artifacts/performance/ 2>/dev/null || echo "No performance artifacts"
ls -lh artifacts/screenshots/ 2>/dev/null || echo "No screenshot artifacts"

echo ""
echo "🎯 Next steps:"
echo "1. Review coverage report: open artifacts/coverage/index.html"
echo "2. Review Playwright report: open playwright-report/index.html"
echo "3. Review k6 results: cat artifacts/performance/k6-results.json"
echo "4. Review Lighthouse: open artifacts/performance/lighthouse.report.html"
echo "5. Review axe results: cat artifacts/performance/axe-results.json"
