// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bawzqrzjppwwwkezumfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhd3pxcnpqcHB3d3drZXp1bWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MjgxNzAsImV4cCI6MjA4NTIwNDE3MH0.rYJ2vzMP5TuMykx5sXIY-bmZvOCgtOA_Stsxq6RwQFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});